# 由引擎维护采样率转换库的目标与配置头生成，不进入上游自己的构建入口。

set(SAMPLERATE_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/../libsamplerate")
# 探针生成文件与最终库留在二进制树，不向第三方源码写入 config.h。
set(SAMPLERATE_BIN_DIR "${CMAKE_BINARY_DIR}/3rdpty/libsamplerate")

file(MAKE_DIRECTORY "${SAMPLERATE_BIN_DIR}")
# 探针缓存使用通用 HAVE_* 名称，同一配置中其他依赖可能已写入同名结果。 若工具链或依赖探针约定改变，应重新配置干净构建树，避免把旧缓存当新探测。

# 以下探针使用当前 CMake 工具链，交叉编译时结果应描述目标平台而非宿主。
include(CheckIncludeFile)
include(CheckFunctionExists)
include(CheckTypeSize)
include(TestBigEndian)
# 此入口只在源码依赖模式创建目标，预编译模式由独立 Find 模块提供同名包装。

# 头可用性分别记录；缺失某个 POSIX 头不表示整个目标不可构建。
check_include_file(inttypes.h HAVE_INTTYPES_H)
check_include_file(stdint.h HAVE_STDINT_H)
# 标准内存与字符串接口的头文件标志，与下面函数链接探针互不替代。
check_include_file(stdlib.h HAVE_STDLIB_H)
check_include_file(string.h HAVE_STRING_H)
# Windows 不必具有全部 sys/unistd 头，未命中的宏后续保持未定义。
check_include_file(sys/stat.h HAVE_SYS_STAT_H)
check_include_file(sys/types.h HAVE_SYS_TYPES_H)
check_include_file(unistd.h HAVE_UNISTD_H)
# 头存在与函数可链接是不同条件，不能仅由 stdlib.h 的结果推导舍入能力。

if(MSVC)
  # MSVC 分支直接声明舍入接口可用，不运行 lrint/lrintf 链接探针。
  set(HAVE_LRINT 1)
  set(HAVE_LRINTF 1)
else()
  # 仅这两次舍入探针显式链接 libm；后续 floor/ceil 不继承这个临时设置。
  set(CMAKE_REQUIRED_LIBRARIES m)
  check_function_exists(lrint HAVE_LRINT)
  check_function_exists(lrintf HAVE_LRINTF)
  # 这里清除而非保存并恢复父值，调用入口不能依赖此前设置继续生效。
  unset(CMAKE_REQUIRED_LIBRARIES)
endif()

# 函数存在性来自配置期链接检查，不是对音频算法正确性的运行测试。
check_function_exists(memcpy HAVE_MEMCPY)
check_function_exists(memmove HAVE_MEMMOVE)
check_function_exists(floor HAVE_FLOOR)
check_function_exists(ceil HAVE_CEIL)
# 链接探针失败可能来自缺少数学库，而非平台绝对没有该函数，排查需看探针日志。

# 将目标数据模型写入配置头，避免使用宿主 Python 或 shell 的类型宽度。
check_type_size(double SIZEOF_DOUBLE)
check_type_size(float SIZEOF_FLOAT)
check_type_size(int SIZEOF_INT)
# long 在 Windows 与常见 Unix 的 64 位 ABI 中可能不同，必须单独探测。
check_type_size(long SIZEOF_LONG)
# 这些大小用于编译条件，不构成音频文件格式约定；文件样本格式由解码层处理。

test_big_endian(CPU_IS_BIG_ENDIAN)
if(CPU_IS_BIG_ENDIAN)
  # 内部变量成对互斥；生成头时只输出值为真的一侧，另一侧并不写成 0。
  set(HAVE_CPU_IS_BIG_ENDIAN 1)
  set(HAVE_CPU_IS_LITTLE_ENDIAN 0)
else()
  # 未判为大端即走小端分支，未知平台应审查探针结果，不能仅凭配置成功验收。
  set(HAVE_CPU_IS_BIG_ENDIAN 0)
  set(HAVE_CPU_IS_LITTLE_ENDIAN 1)
endif()

if(WIN32)
  # WIN32 指目标平台，交叉编译到 Windows 时同样需要该兼容宏。
  set(HAVE_OS_IS_WIN32 1)
else()
  set(HAVE_OS_IS_WIN32 0)
endif()

# 配置头由能力宏和 ABI 常量两部分组成；生成文件本身不纳入自维护注释率。
set(CONFIG_H_CONTENT "/* Generated by Buildlibsamplerate.cmake */\n")
foreach(
  var
  # 标准和 POSIX 头探针只控制包含路径分支，不替调用方提供缺失的系统头。
  HAVE_INTTYPES_H
  HAVE_STDINT_H
  HAVE_STDLIB_H
  HAVE_STRING_H
  HAVE_SYS_STAT_H
  HAVE_SYS_TYPES_H
  HAVE_UNISTD_H
  # 舍入与内存函数标志描述可用接口，不能与是否启用某一种重采样器混淆。
  HAVE_LRINT
  HAVE_LRINTF
  HAVE_MEMCPY
  HAVE_MEMMOVE
  HAVE_FLOOR
  HAVE_CEIL
  # 架构和 OS 标志来自目标工具链，不能从输出目录名字重新推测。
  HAVE_CPU_IS_BIG_ENDIAN
  HAVE_CPU_IS_LITTLE_ENDIAN
  HAVE_OS_IS_WIN32)
  if(${var})
    # 有意省略假值宏，保持 #ifdef 与能力检测一致；不能统一输出 #define ... 0。
    string(APPEND CONFIG_H_CONTENT "#define ${var} 1\n")
  endif()
endforeach()

# 类型宽度无条件输出；若探针失败，需检查生成值而非把它当作有效默认宽度。
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_DOUBLE ${SIZEOF_DOUBLE}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_FLOAT ${SIZEOF_FLOAT}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_INT ${SIZEOF_INT}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_LONG ${SIZEOF_LONG}\n")
# 包名与版本是此脚本固定的兼容元数据，不是从当前上游源码自动读取的版本。
string(APPEND CONFIG_H_CONTENT "#define PACKAGE \"libsamplerate\"\n")
string(APPEND CONFIG_H_CONTENT "#define VERSION \"0.1.9\"\n")
# 正负裁剪能力均设为 0，不能假定 CPU 的浮点转整数行为会自动饱和。
string(APPEND CONFIG_H_CONTENT "#define CPU_CLIPS_POSITIVE 0\n")
string(APPEND CONFIG_H_CONTENT "#define CPU_CLIPS_NEGATIVE 0\n")
# 配置文本是编译输入而非运行时选项，修改探测或常量后需要重新编译库实现。

# 每次配置整体重写派生头；多套工具链必须使用隔离的构建目录。
file(WRITE "${SAMPLERATE_BIN_DIR}/config.h" "${CONFIG_H_CONTENT}")

# libsamplerate 源码目录缺少可直接复用的现代 CMake 目标，这里手动跟随 ICE_LINKAGE 产出静态库或 DLL。
set(SAMPLERATE_LIBRARY_TYPE STATIC)
# 外部源文件直接作为本工程目标参与编译，业务 PGO 选项不得从目录级传播到此目标。
if(ICE_LINKAGE STREQUAL "shared")
  # 库类型直接反映引擎偏好，不另设可能与之冲突的上游缓存开关。
  set(SAMPLERATE_LIBRARY_TYPE SHARED)
endif()

add_library(
  samplerate
  ${SAMPLERATE_LIBRARY_TYPE}
  # 固定列出实现文件，避免 glob 将上游示例、测试或新增程序自动带入目标。
  "${SAMPLERATE_SRC_DIR}/src/samplerate.c"
  # 各插值实现合入同一库，由公共 API 选择模式，不为每种算法另建目标。
  "${SAMPLERATE_SRC_DIR}/src/src_sinc.c"
  "${SAMPLERATE_SRC_DIR}/src/src_zoh.c"
  "${SAMPLERATE_SRC_DIR}/src/src_linear.c")

# 三类产物统一进入构建私有目录；该目录不是按平台/配置划分的发布包布局。
set_target_properties(
  samplerate
  # ARCHIVE 同时覆盖静态库和 Windows 导入库，RUNTIME 对应 Windows DLL。
  PROPERTIES ARCHIVE_OUTPUT_DIRECTORY "${SAMPLERATE_BIN_DIR}"
             LIBRARY_OUTPUT_DIRECTORY "${SAMPLERATE_BIN_DIR}"
             RUNTIME_OUTPUT_DIRECTORY "${SAMPLERATE_BIN_DIR}")
# 多配置生成器可能在公共输出目录下附加配置子目录，消费方应链接目标而非拼路径。
if(ICE_LINKAGE STREQUAL "shared" AND WIN32)
  # Windows 动态库自动导出符号，避免仅生成 DLL 却没有可供消费者链接的入口。
  set_target_properties(samplerate PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
endif()

# 源码头与生成配置目录当前都向消费者公开，包装接口也会传递这些路径。
target_include_directories(samplerate PUBLIC "${SAMPLERATE_SRC_DIR}/src"
                                             "${SAMPLERATE_BIN_DIR}")
# 只有库实现需要主动包含 config.h，不把 HAVE_CONFIG_H 宏泄漏到业务目标。
target_compile_definitions(samplerate PRIVATE HAVE_CONFIG_H)
# 此脚本没有另设私有 CRT 偏好，Windows 运行库一致性由父级配置负责。

if(UNIX AND NOT APPLE)
  # Linux 等 Unix 的数学符号由 libm 提供；Apple 不使用独立的 m 链接项。
  target_link_libraries(samplerate PRIVATE m)
endif()

add_library(3rd_libsamplerate INTERFACE)
# 创建真实目标后再包装，CMake 可自动安排构建顺序，无须对归档文件手写依赖。 稳定消费名与预编译模式相同，头路径及链接要求由 samplerate
# 目标继续传播。
target_link_libraries(3rd_libsamplerate INTERFACE samplerate)
