# 3rdpty/sources/cmake/Buildzlib.cmake

include(ExternalProject)

set(ICE_ZLIB_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../zlib")
set(ICE_ZLIB_BINARY_DIR "${CMAKE_BINARY_DIR}/3rdpty/zlib_bld")
set(ICE_ZLIB_INSTALL_DIR "${CMAKE_BINARY_DIR}/3rdpty/zlib_inst")
set(ICE_ZLIB_INCLUDE_DIR "${ICE_ZLIB_INSTALL_DIR}/include")
set(ICE_ZLIB_LIBRARY_DIR "${ICE_ZLIB_INSTALL_DIR}/lib")
set(ICE_ZLIB_PKGCONFIG_DIR "${ICE_ZLIB_LIBRARY_DIR}/pkgconfig")
set(ICE_ZLIB_SOURCE_STAMP "${ICE_ZLIB_INSTALL_DIR}/.ice_zlib_sources.stamp")
set(ICE_ZLIB_SOURCE_READY_TEST
    "test -f '${ICE_ZLIB_SOURCE_STAMP}' && ! /usr/bin/find '${ICE_ZLIB_SOURCE_DIR}' -type f -newer '${ICE_ZLIB_SOURCE_STAMP}' ! -path '*/.git/*' -print -quit | /usr/bin/grep -q ."
)

string(TOLOWER "${CMAKE_BUILD_TYPE}" ICE_ZLIB_BUILD_TYPE_LOWER)
set(ICE_ZLIB_DEBUG_POSTFIX "")
if(ICE_ZLIB_BUILD_TYPE_LOWER STREQUAL "debug")
  set(ICE_ZLIB_DEBUG_POSTFIX "d")
endif()

if(MSVC)
  set(ICE_ZLIB_STATIC_LIBRARY
      "${ICE_ZLIB_LIBRARY_DIR}/libzs${ICE_ZLIB_DEBUG_POSTFIX}.lib")
elseif(WIN32)
  set(ICE_ZLIB_STATIC_LIBRARY
      "${ICE_ZLIB_LIBRARY_DIR}/libzs${ICE_ZLIB_DEBUG_POSTFIX}.a")
else()
  set(ICE_ZLIB_STATIC_LIBRARY "${ICE_ZLIB_LIBRARY_DIR}/libz.a")
endif()

set(ICE_ZLIB_BUILD_BYPRODUCTS
    "${ICE_ZLIB_STATIC_LIBRARY}" "${ICE_ZLIB_PKGCONFIG_DIR}/zlib.pc"
    "${ICE_ZLIB_SOURCE_STAMP}")
set(ICE_ZLIB_INSTALL_COMMAND "'${CMAKE_COMMAND}' --build . --target install")
if(WIN32)
  set(ICE_ZLIB_COMPAT_LIBRARIES)
  if(MSVC)
    list(APPEND ICE_ZLIB_COMPAT_LIBRARIES "${ICE_ZLIB_LIBRARY_DIR}/libz.lib")
    if(NOT ICE_ZLIB_DEBUG_POSTFIX STREQUAL "")
      list(APPEND ICE_ZLIB_COMPAT_LIBRARIES "${ICE_ZLIB_LIBRARY_DIR}/libzs.lib")
    endif()
  else()
    list(APPEND ICE_ZLIB_COMPAT_LIBRARIES "${ICE_ZLIB_LIBRARY_DIR}/libz.a")
    if(NOT ICE_ZLIB_DEBUG_POSTFIX STREQUAL "")
      list(APPEND ICE_ZLIB_COMPAT_LIBRARIES "${ICE_ZLIB_LIBRARY_DIR}/libzs.a")
    endif()
  endif()

  foreach(compatLibrary IN LISTS ICE_ZLIB_COMPAT_LIBRARIES)
    set(ICE_ZLIB_INSTALL_COMMAND
        "${ICE_ZLIB_INSTALL_COMMAND} && '${CMAKE_COMMAND}' -E copy_if_different '${ICE_ZLIB_STATIC_LIBRARY}' '${compatLibrary}'"
    )
    list(APPEND ICE_ZLIB_BUILD_BYPRODUCTS "${compatLibrary}")
  endforeach()
endif()

ExternalProject_Add(
  zlib_project
  SOURCE_DIR "${ICE_ZLIB_SOURCE_DIR}"
  BINARY_DIR "${ICE_ZLIB_BINARY_DIR}"
  INSTALL_DIR "${ICE_ZLIB_INSTALL_DIR}"
  UPDATE_COMMAND ""
  BUILD_ALWAYS TRUE
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${ICE_ZLIB_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR=lib
             -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
             -DCMAKE_POSITION_INDEPENDENT_CODE=ON
             -DCMAKE_INSTALL_MESSAGE=NEVER
             -DZLIB_BUILD_SHARED=OFF
             -DZLIB_BUILD_STATIC=ON
             -DZLIB_BUILD_TESTING=OFF
             -DZLIB_INSTALL=ON
  BUILD_COMMAND sh -c
                "${ICE_ZLIB_SOURCE_READY_TEST} || '${CMAKE_COMMAND}' --build ."
  INSTALL_COMMAND
    sh -c
    "${ICE_ZLIB_SOURCE_READY_TEST} || (${ICE_ZLIB_INSTALL_COMMAND} && '${CMAKE_COMMAND}' -E touch '${ICE_ZLIB_SOURCE_STAMP}')"
  BUILD_BYPRODUCTS ${ICE_ZLIB_BUILD_BYPRODUCTS})

file(MAKE_DIRECTORY "${ICE_ZLIB_INCLUDE_DIR}")
file(MAKE_DIRECTORY "${ICE_ZLIB_LIBRARY_DIR}")
file(MAKE_DIRECTORY "${ICE_ZLIB_PKGCONFIG_DIR}")

add_library(3rd_zlib INTERFACE)
add_dependencies(3rd_zlib zlib_project)
target_include_directories(3rd_zlib INTERFACE "${ICE_ZLIB_INCLUDE_DIR}")
target_link_libraries(3rd_zlib INTERFACE "${ICE_ZLIB_STATIC_LIBRARY}")
