# 3rdpty/sources/cmake/Buildlibsamplerate.cmake

set(SAMPLERATE_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/../libsamplerate")
set(SAMPLERATE_BIN_DIR "${CMAKE_BINARY_DIR}/3rdpty/libsamplerate")

file(MAKE_DIRECTORY "${SAMPLERATE_BIN_DIR}")

# Perform checks to generate config.h content
include(CheckIncludeFile)
include(CheckFunctionExists)
include(CheckTypeSize)
include(TestBigEndian)

check_include_file(inttypes.h HAVE_INTTYPES_H)
check_include_file(stdint.h HAVE_STDINT_H)
check_include_file(stdlib.h HAVE_STDLIB_H)
check_include_file(string.h HAVE_STRING_H)
check_include_file(sys/stat.h HAVE_SYS_STAT_H)
check_include_file(sys/types.h HAVE_SYS_TYPES_H)
check_include_file(unistd.h HAVE_UNISTD_H)

if(MSVC)
  set(HAVE_LRINT 1)
  set(HAVE_LRINTF 1)
else()
  set(CMAKE_REQUIRED_LIBRARIES m)
  check_function_exists(lrint HAVE_LRINT)
  check_function_exists(lrintf HAVE_LRINTF)
  unset(CMAKE_REQUIRED_LIBRARIES)
endif()

check_function_exists(memcpy HAVE_MEMCPY)
check_function_exists(memmove HAVE_MEMMOVE)
check_function_exists(floor HAVE_FLOOR)
check_function_exists(ceil HAVE_CEIL)

check_type_size(double SIZEOF_DOUBLE)
check_type_size(float SIZEOF_FLOAT)
check_type_size(int SIZEOF_INT)
check_type_size(long SIZEOF_LONG)

test_big_endian(CPU_IS_BIG_ENDIAN)
if(CPU_IS_BIG_ENDIAN)
  set(HAVE_CPU_IS_BIG_ENDIAN 1)
  set(HAVE_CPU_IS_LITTLE_ENDIAN 0)
else()
  set(HAVE_CPU_IS_BIG_ENDIAN 0)
  set(HAVE_CPU_IS_LITTLE_ENDIAN 1)
endif()

if(WIN32)
  set(HAVE_OS_IS_WIN32 1)
else()
  set(HAVE_OS_IS_WIN32 0)
endif()

# Prepare config.h content
set(CONFIG_H_CONTENT "/* Generated by Buildlibsamplerate.cmake */\n")
foreach(
  var
  HAVE_INTTYPES_H
  HAVE_STDINT_H
  HAVE_STDLIB_H
  HAVE_STRING_H
  HAVE_SYS_STAT_H
  HAVE_SYS_TYPES_H
  HAVE_UNISTD_H
  HAVE_LRINT
  HAVE_LRINTF
  HAVE_MEMCPY
  HAVE_MEMMOVE
  HAVE_FLOOR
  HAVE_CEIL
  HAVE_CPU_IS_BIG_ENDIAN
  HAVE_CPU_IS_LITTLE_ENDIAN
  HAVE_OS_IS_WIN32)
  if(${var})
    string(APPEND CONFIG_H_CONTENT "#define ${var} 1\n")
  endif()
endforeach()

string(APPEND CONFIG_H_CONTENT "#define SIZEOF_DOUBLE ${SIZEOF_DOUBLE}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_FLOAT ${SIZEOF_FLOAT}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_INT ${SIZEOF_INT}\n")
string(APPEND CONFIG_H_CONTENT "#define SIZEOF_LONG ${SIZEOF_LONG}\n")
string(APPEND CONFIG_H_CONTENT "#define PACKAGE \"libsamplerate\"\n")
string(APPEND CONFIG_H_CONTENT "#define VERSION \"0.1.9\"\n")
string(APPEND CONFIG_H_CONTENT "#define CPU_CLIPS_POSITIVE 0\n")
string(APPEND CONFIG_H_CONTENT "#define CPU_CLIPS_NEGATIVE 0\n")

file(WRITE "${SAMPLERATE_BIN_DIR}/config.h" "${CONFIG_H_CONTENT}")

# Define the library target manually
add_library(
  samplerate STATIC
  "${SAMPLERATE_SRC_DIR}/src/samplerate.c"
  "${SAMPLERATE_SRC_DIR}/src/src_sinc.c" "${SAMPLERATE_SRC_DIR}/src/src_zoh.c"
  "${SAMPLERATE_SRC_DIR}/src/src_linear.c")

set_target_properties(samplerate PROPERTIES ARCHIVE_OUTPUT_DIRECTORY
                                            "${SAMPLERATE_BIN_DIR}")

target_include_directories(samplerate PUBLIC "${SAMPLERATE_SRC_DIR}/src"
                                             "${SAMPLERATE_BIN_DIR}")
target_compile_definitions(samplerate PRIVATE HAVE_CONFIG_H)

if(UNIX AND NOT APPLE)
  target_link_libraries(samplerate PRIVATE m)
endif()

add_library(3rd_libsamplerate INTERFACE)
target_link_libraries(3rd_libsamplerate INTERFACE samplerate)
